#"Boot with standard options"  "archisobasedir=arch archisosearchuuid=2025-10-01-16-09-23-00"
#"Boot to single-user mode"    "archisobasedir=arch archisosearchuuid=2025-10-01-16-09-23-00 single"
"Boot with standard options"	"ro root=UUID=abc7cf8f-4f49-4d5e-a672-4b026a7c05ca"	
"Boot with minimal options"   "ro root=UUID=abc7cf8f-4f49-4d5e-a672-4b026a7c05ca"
